global:
  scrape_interval:     20s
  evaluation_interval: 20s

  external_labels:
    monitor: 'prometheus_speedtest-exporter'

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090']

- job_name: 'speedtest-exporter'
  static_configs:
  - targets: ['192.168.20.64:9469']

- job_name: 'speedtest'
  metrics_path: /probe
  params:
    script: [speedtest]
  static_configs:
  - targets: ['192.168.20.64:9469']
  scrape_interval: 120s
  scrape_timeout: 90s
